site_name: 'project name'

theme:
  name: 'material'

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Checkboxes
  - pymdownx.tasklist:
      custom_checkbox: true
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  # Navigation page ordering
  - awesome-pages
  - search

copyright: |
  project owner